apiVersion: apps/v1
kind: Deployment
metadata:
  name: karsajobs-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: karsajobs
  template:
    metadata:
      labels:
        app: karsajobs
    spec:
      containers:
        - name: karsajobs
          image: ghcr.io/vikiwahyudi12/karsajobs:latest
          ports:
            - containerPort: 8080
          env:
            - name: APP_PORT
              value: "8080"
            - name: DB_HOST
              value: "mongo-service"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: MONGO_ROOT_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: MONGO_ROOT_PASSWORD