apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shipping-service
  template:
    metadata:
      labels:
        app: shipping-service
    spec:
      containers:
      - name: shipping-service
        image: ghcr.io/vikiwahyudi12/shipping-service:latest
        env:
        - name: AMQP_URL
          value: "amqp://guest:guest@rabbitmq:5672"